apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: url-shortener
data:
  mongodb.conf: |
    storage:
      dbPath: /bitnami/mongodb/data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
      replSetName: rs0
